### ISSUE TITLE
Incomplete example on "Client ID Enforcement Policy: Obtaining Credentials Using Basic Authorization header"

### ISSUE THREAD

**Issue by mtcarvalho** [mulesoft/docs-api-manager#373]
The "[Obtaining Credentials Using Basic Authorization header](https://docs.mulesoft.com/api-manager/2.x/client-id-based-policies#obtaining-credentials-using-basic-authorization-header)" section don't have the Dataweave 2.0 Example, just like the previous sections. Looks like it is missing information there.

**Comment by chris-campbell9** [comment]
Hi @mtcarvalho,

Thanks so much for contacting us!

If you select the basic authentication option in the Client ID Enforcement Policy, there is no way to manually input a  DataWeave expression because credentials are obtained automatically. This is why there is no DataWeave expression in the corresponding section of the documentation.

That said, it might be a good idea for us to explain this in the documentation. I'll open a new PR with the change, and close this issue.

Thanks again!

Regards,
Chris Campbell

**Comment by mtcarvalho** [comment]
Oh, ok @chris-campbell9. I felt that something was missing but I didn't know that is not possible to use DataWeave expressions in this case. Really, it could be nice if you could explain this in docs.
